spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
  application:
    name: product-catalog

product:
  search:
    base-url: http://localhost:8081
    api:
      update-index: /search/update-index