spring:
  cloud:
    function:
      definition: productProducer
    stream:
      poller:
        fixed-delay: 5000
      bindings:
        productProducer-out-0:
          destination: product/index/update
          binder: local-solace
      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: tcp://localhost:55555
                msgVpn: default
                clientUsername: default
                clientPassword: default
                connectRetries: -1
                reconnectRetries: -1